name: Setup Doodle

inputs:
  ref:
    description: 'The ref to checkout'
    required: false
    default: 'main'

runs:
  using: "composite"
  steps:
    - name: Checkout deepinthink/doodle
      uses: actions/checkout@v4
      with:
        repository: deepinthink/doodle
        path: deepinthink/doodle
        ref: ${{ inputs.ref }}

    - name: Build && Install doodle-specification-bi
      shell: bash
      run: cd deepinthink/doodle/specification/bi/java/doodle-specification-bi && ./mvnw install -B

    - name: Build && Install doodle-specification-component
      shell: bash
      run: cd deepinthink/doodle/specification/component/java/doodle-specification-component && ./mvnw install -B

    - name: Build && Install doodle-specification-game
      shell: bash
      run: cd deepinthink/doodle/specification/game/java/doodle-specification-game && ./mvnw install -B

    - name: Build && Install doodle-specification-sdk
      shell: bash
      run: cd deepinthink/doodle/specification/sdk/java/doodle-specification-sdk && ./mvnw install -B

    - name: Build && Install doodle-specification-service
      shell: bash
      run: cd deepinthink/doodle/specification/service/java/doodle-specification-service && ./mvnw install -B

    - name: Build && Install doodle-spring-game
      shell: bash
      run: cd deepinthink/doodle/infrastructure/framework/java/doodle-spring-game && ./mvnw install -B

    - name: Build && Install doodle-spring-game-bi
      shell: bash
      run: cd deepinthink/doodle/infrastructure/bi/java/doodle-spring-game-bi && ./mvnw install -B

    - name: Build && Install doodle-spring-game-sdk-login
      shell: bash
      run: cd deepinthink/doodle/sdks/login/java/doodle-spring-game-sdk-login && ./mvnw install -B

    - name: Build && Install doodle-spring-game-sdk-payment
      shell: bash
      run: cd deepinthink/doodle/sdks/payment/java/doodle-spring-game-sdk-payment && ./mvnw install -B

    - name: Build && Install doodle-spring-game-service-giftcode
      shell: bash
      run: cd deepinthink/doodle/services/giftcode/java/doodle-spring-game-service-giftcode && ./mvnw install -B

    - name: Build && Install doodle-spring-game-service-login
      shell: bash
      run: cd deepinthink/doodle/services/login/java/doodle-spring-game-service-login && ./mvnw install -B

    - name: Build && Install doodle-spring-game-service-mail
      shell: bash
      run: cd deepinthink/doodle/services/mail/java/doodle-spring-game-service-mail && ./mvnw install -B

    - name: Build && Install doodle-spring-game-service-notice
      shell: bash
      run: cd deepinthink/doodle/services/notice/java/doodle-spring-game-service-notice && ./mvnw install -B

    - name: Build && Install doodle-spring-game-service-payment
      shell: bash
      run: cd deepinthink/doodle/services/payment/java/doodle-spring-game-service-payment && ./mvnw install -B

    - name: Build && Install doodle-spring-game-service-role
      shell: bash
      run: cd deepinthink/doodle/services/role/java/doodle-spring-game-service-role && ./mvnw install -B

    - name: Build && Install doodle-specification-game
      shell: bash
      run: cd deepinthink/doodle/specification/game/java/doodle-specification-game && ./mvnw install -B

    - name: Build && Install doodle-spring-game-chess
      shell: bash
      run: cd deepinthink/doodle/templates/chess/java/doodle-spring-game-chess && ./mvnw install -B

    - name: Build && Install doodle-spring-game-idle
      shell: bash
      run: cd deepinthink/doodle/templates/idle/java/doodle-spring-game-idle && ./mvnw install -B

    - name: Build && Install doodle-benchmark
      shell: bash
      run: cd deepinthink/doodle/templates/benchmark/java/doodle-benchmark && ./mvnw install -B

    - name: Build && Install doodle-initializr
      shell: bash
      run: cd deepinthink/doodle/tools/initializr/java/doodle-initializr && ./mvnw install -B
