name: CI Maven

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '25'
          cache: 'maven'

      - name: Setup deepinthink/amoeba
        uses: deepinthink/amoeba/.github/actions/setup-amoeba/java@main

      - name: Build && Install doodle-specification-bi
        run: cd specification/bi/java/doodle-specification-bi && ./mvnw install -B

      - name: Build && Install doodle-specification-component
        run: cd specification/component/java/doodle-specification-component && ./mvnw install -B

      - name: Build && Install doodle-specification-game
        run: cd specification/game/java/doodle-specification-game && ./mvnw install -B

      - name: Build && Install doodle-specification-sdk
        run: cd specification/sdk/java/doodle-specification-sdk && ./mvnw install -B

      - name: Build && Install doodle-specification-service
        run: cd specification/service/java/doodle-specification-service && ./mvnw install -B

      - name: Build && Install doodle-spring-game
        run: cd infrastructure/framework/java/doodle-spring-game && ./mvnw install -B

      - name: Build && Install doodle-spring-game-bi
        run: cd infrastructure/bi/java/doodle-spring-game-bi && ./mvnw install -B

      - name: Build && Install doodle-spring-game-sdk-login
        run: cd sdks/login/java/doodle-spring-game-sdk-login && ./mvnw install -B

      - name: Build && Install doodle-spring-game-sdk-payment
        run: cd sdks/payment/java/doodle-spring-game-sdk-payment && ./mvnw install -B

      - name: Build && Install doodle-spring-game-service-giftcode
        run: cd services/giftcode/java/doodle-spring-game-service-giftcode && ./mvnw install -B

      - name: Build && Install doodle-spring-game-service-login
        run: cd services/login/java/doodle-spring-game-service-login && ./mvnw install -B

      - name: Build && Install doodle-spring-game-service-mail
        run: cd services/mail/java/doodle-spring-game-service-mail && ./mvnw install -B

      - name: Build && Install doodle-spring-game-service-notice
        run: cd services/notice/java/doodle-spring-game-service-notice && ./mvnw install -B

      - name: Build && Install doodle-spring-game-service-payment
        run: cd services/payment/java/doodle-spring-game-service-payment && ./mvnw install -B

      - name: Build && Install doodle-spring-game-service-role
        run: cd services/role/java/doodle-spring-game-service-role && ./mvnw install -B

      - name: Build && Install doodle-specification-game
        run: cd specification/game/java/doodle-specification-game && ./mvnw install -B

      - name: Build && Install doodle-spring-game-chess
        run: cd templates/chess/java/doodle-spring-game-chess && ./mvnw install -B

      - name: Build && Install doodle-spring-game-idle
        run: cd templates/idle/java/doodle-spring-game-idle && ./mvnw install -B

      - name: Build && Install doodle-benchmark
        run: cd templates/benchmark/java/doodle-benchmark && ./mvnw install -B

      - name: Build && Install doodle-initializr
        run: cd tools/initializr/java/doodle-initializr && ./mvnw install -B
